from sqlalchemy import Column, String, Float
from core.models.base_model import BaseModel


class DataFacilityTwo(BaseModel):
    __tablename__ = "data_facility_two"

    record_date = Column(String, primary_key=True, index=True)
    value_1 = Column(Float)
    value_2 = Column(Float)
    value_3 = Column(Float)
    value_4 = Column(Float)
    value_5 = Column(Float)
    value_6 = Column(Float)
    value_7 = Column(Float)
    value_8 = Column(Float)
    value_9 = Column(Float)
    value_10 = Column(Float)
    value_11 = Column(Float)
    value_12 = Column(Float)
    value_13 = Column(Float)
    value_14 = Column(Float)
    value_15 = Column(Float)
    value_16 = Column(Float)
    value_17 = Column(Float)
    value_18 = Column(Float)
    value_19 = Column(Float)
    value_20 = Column(Float)
    value_21 = Column(Float)
    value_22 = Column(Float)
    value_23 = Column(Float)
    value_24 = Column(Float)
    value_25 = Column(Float)
    value_26 = Column(Float)
    value_27 = Column(Float)
    value_28 = Column(Float)
    value_29 = Column(Float)
    value_30 = Column(Float)
    value_31 = Column(Float)
    value_32 = Column(Float)
    value_33 = Column(Float)
    value_34 = Column(Float)
    value_35 = Column(Float)
    value_36 = Column(Float)
    value_37 = Column(Float)
    value_38 = Column(Float)
    value_39 = Column(Float)
    value_40 = Column(Float)
    value_41 = Column(Float)
    value_42 = Column(Float)
    value_43 = Column(Float)
    value_44 = Column(Float)
    value_45 = Column(Float)
    value_46 = Column(Float)
    value_47 = Column(Float)
    value_48 = Column(Float)