name: Build and Deploy Python Function App to Azure

on:
  # Kích hoạt khi có push lên nhánh main
  push:
    branches:
      - main
  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Deploy to Azure Functions'
        id: deploy-to-function
        uses: Azure/functions-action@v1
        with:
          # Tên Function App của bạn trên Azure
          app-name: 'saiene-deploy'
          
          # Trỏ đến thư mục gốc của repo để đóng gói.
          package: '.'
          
          # "Chìa khóa" để đăng nhập vào Azure
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          
          # Cấu hình đặc biệt cho gói Flex Consumption
          sku: flexconsumption
          
          # Yêu cầu Azure tự build ứng dụng sau khi nhận code
          remote-build: true
